### ISSUE TITLE
DB connection does not work on Cloudfoundry

### ISSUE THREAD

**Issue by imod** [dickerpulli/spring-batch-admin-spring-boot#1]
Have you ever tried to get this to work on Cloudfoundry?
The app is not able to establish the connection to the database - the same database connection (service definition) is working for other none boot applications.

```
2014-12-22T11:50:13.10+0100 [App/0]   ERR Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
2014-12-22T11:50:13.10+0100 [App/0]   ERR The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   ... 55 more
2014-12-22T11:50:13.10+0100 [App/0]   ERR Caused by: java.net.ConnectException: Connection refused
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at java.net.PlainSocketImpl.socketConnect(Native Method)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at java.net.Socket.connect(Socket.java:589)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at java.net.Socket.connect(Socket.java:538)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at java.net.Socket.<init>(Socket.java:434)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at java.net.Socket.<init>(Socket.java:244)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:243)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
2014-12-22T11:50:13.10+0100 [App/0]   ERR   ... 71 more
2014-12-22T11:50:13.38+0100 [DEA]     ERR Instance (index 0) failed to start accepting connections
```

**Comment by dickerpulli** [comment]
Consider moving to Spring Cloud Data Flow like Spring recommends for Spring Batch Admin users.
See https://github.com/spring-projects/spring-batch-admin
